Develop
Alynn9/portfolio pull request #1
Opened 2022-10-15 09:50 UTC by Alynn9

Angular portfolio

2022-10-19 08:26 UTC, Khousheish reviewed
Good job overall
some minor fixes still needed lots of inconsistent indentation

2022-10-19 08:26 UTC, Khousheish commented on src/app/app.component.ts
> +  constructor(){}
remove empty constructor

2022-10-19 08:26 UTC, Khousheish commented on src/app/app.component.ts
> +
remove

2022-10-19 08:26 UTC, Khousheish commented on src/app/app.component.ts
> +
remove

2022-10-19 08:26 UTC, Khousheish commented on src/app/app.component.ts
> +  testimonialsArray:any = [
you can ad a type here for the testimonials
also move the variable above the methods

2022-10-20 19:54 UTC, Chrishalaby approved these changes

2022-10-30 19:34 UTC, Khousheish requested changes

2022-10-30 19:34 UTC, Khousheish commented on src/app/app.component.html
> +<app-footer></app-footer>
why did you only move the footer and intro to separate components? you could do this for everything here

2022-10-30 19:34 UTC, Khousheish commented on src/app/app.component.scss
> +.about-me {
move all these styles to their own components

2022-10-30 19:34 UTC, Khousheish commented on src/app/footer/footer.component.scss
> +$pink: rgba(240, 131, 183, 0.911);
you dont have to redefine all the colors again this is redundant

2022-10-30 19:34 UTC, Khousheish commented on src/app/footer/footer.component.ts
> +  constructor() { }
remove constructor and oninit if they are empty

2022-10-30 19:34 UTC, Khousheish commented on src/app/intro/intro.component.html
> +</div>
EOL check rest of the files

2022-10-30 19:34 UTC, Khousheish commented on src/app/intro/intro.component.ts
> +  constructor() { }
as above

2022-11-13 17:12 UTC, Khousheish requested changes

2022-11-13 17:12 UTC, Khousheish commented on README.md
> +# Assignment-1
remove this

2022-11-13 17:12 UTC, Khousheish commented on src/app/about-me/about-me.component.scss
> +}
move this block to a global section since its shared across everything

2022-11-13 17:12 UTC, Khousheish commented on src/app/about-me/about-me.component.ts
> +  ngOnInit(): void {
remove empty functions if they are empty

2022-11-13 17:12 UTC, Khousheish commented on src/app/above-footer/above-footer.component.scss
> +}
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/above-footer/above-footer.component.ts
> +  ngOnInit(): void {
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/app.component.ts
> +  ngOnInit(){
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/footer/footer.component.scss
> +}
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/footer/footer.component.ts
> +  ngOnInit(): void {
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/intro/intro.component.scss
> +}
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/intro/intro.component.ts
> +  ngOnInit(): void {
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/my-recent-work/my-recent-work.component.scss
> +}
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/my-recent-work/my-recent-work.component.ts
> +  ngOnInit(): void {
remove

2022-11-13 17:12 UTC, Khousheish commented on src/app/testimonials/testimonials.component.scss
> +}
remove

2022-11-27 12:24 UTC, Khousheish approved these changes
some minor comments but looks good

2022-11-27 12:24 UTC, Khousheish commented on README.md
> +# Assignment-1
wasnt removed

2022-11-27 12:24 UTC, Khousheish commented on src/app/footer/footer.component.ts
> +}
EOF

2022-11-27 15:46 UTC, merged